[theme]
primaryColor = "#FF4B4B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[theme.sidebar]
widgetBackgroundColor = "#F0F2F6"
widgetBorderColor = "#E0E0E0"
skeletonBackgroundColor = "#E0E0E0"

[server]
headless = true
